### ISSUE TITLE
QST: Maturity level of spyndex

### ISSUE THREAD

**Issue by remi-braun** [awesome-spectral-indices/spyndex#13]
Hello,

I would like to use your library in [eoreader](https://github.com/sertit/eoreader), to replace my own way of computing spectral indices.
I see that in `setup.py` you still are in pre-alpha mode, but according to your code, documentation and README, you seems pretty well advanced.

So, should I wait an API stabilization ? Or am I good to go ? 😄

**Comment by davemlz** [comment]
Hi @remi-braun!

The API is mature enough ;) I just like to keep the mode like that in case of minor upgrades and stuff. If you want to use it, please, be my guest! :rocket: 

By the way, nice job with [eoreader](https://github.com/sertit/eoreader)!

If you have further questions, please let me know.

PD: When you have it done also let me know! I keep a track of resources that use Awesome Spectral Indices [here](https://github.com/awesome-spectral-indices/awesome-spectral-indices#used-by) so the community can also check them ;)

Cheers!

Dave

**Comment by remi-braun** [comment]
Thanks for the quick answer!

I will let you know 😄
