### ISSUE TITLE
Something wrong with NDWI

### ISSUE THREAD

**Issue by abreufilho** [awesome-spectral-indices/spyndex#14]
Hello, i've been trying to use the computeIndex for NDWI but apart from all other indexes working well, NDWI has been presenting issues so i've tested every way to compute it correctly but it seems something's wrong.

The image below shows the test i've made using the same variables but computeIndex returning the wrong range of values:

![image](https://user-images.githubusercontent.com/54593418/192002211-0c02c113-66ad-4248-9096-3e2b9e7a0b06.png)

**Comment by abreufilho** [comment]
UPDATE: Appears to be an issue with rasterio reading the band without casting ".astype(float)".

Using `src.read(band_index).astype(float)` fixed it for me.

**Comment by davemlz** [comment]
Perfect!

I'm closing this issue. Please re-open it if you find it again working wrong ;)

Best,

David
