### ISSUE TITLE
QST: Compute custom spectral indices

### ISSUE THREAD

**Issue by remi-braun** [awesome-spectral-indices/spyndex#16]
Hello,

Is it possible to compute custom indices that are not registered in [Awesome Spectral Indices](https://awesome-ee-spectral-indices.readthedocs.io/en/latest/index.html) ?

My usecase is that I have maybe too specific indices that wouldn't be useful to the community.
Or indices using satellites not handled currently like WorldViews/PlanetScope with the Yellow band.

If not I would be happy to share them all 😄

**Comment by remi-braun** [comment]
For example, I need to allow all [these satellites](https://eoreader.readthedocs.io/en/latest/optical_band_mapping.html) (with their mapped bands) to have indices.

Maxar has developped spectral indices based on their bands (you can see them page 2 [here](https://resources.maxar.com/optical-imagery/multispectral-reference-guide))
Would it be useful for you to add a Yellow band ?

**Comment by davemlz** [comment]
Hi @remi-braun,

For now it is not possible. The idea would be to add the indices to ASI first.

About the `Yellow` band. It seems fair to have it. Let me some time I rearrange the structure in ASI for this :)

**Comment by davemlz** [comment]
Hi @remi-braun!

I added a `Yellow` band in Awesome Spectral Indices (https://github.com/awesome-spectral-indices/awesome-spectral-indices/issues/24). The standard for the band is `Y` :)

Cheers!

**Comment by remi-braun** [comment]
> Hi @remi-braun,
> 
> For now it is not possible. The idea would be to add the indices to ASI first.
> 
> About the `Yellow` band. It seems fair to have it. Let me some time I rearrange the structure in ASI for this :)

Ok I try to add a maximum of the indices provided in EOReader, but I think some are too contextual.
I will try to mimic you mechanism to add other indices then 🙂

NB: If you could add the `water vapour` band in ASI, it would be great! 🙏
