### ISSUE TITLE
spyndex.plot.heatmap not working

### ISSUE THREAD

**Issue by vsilva89** [awesome-spectral-indices/spyndex#18]
Hi, I'm trying to replicate the plot heatmap example but it doesn't work 

![image](https://github.com/awesome-spectral-indices/spyndex/assets/19230387/b537ebd8-5be2-4dd2-b2dd-fb60de51fb09)

**Comment by davemlz** [comment]
Fixed!

It will be available in the next version of spyndex! ;)
