### ISSUE TITLE
Error while running the toy example

### ISSUE THREAD

**Issue by Aca-Ali** [awesome-spectral-indices/spyndex#21]
I am trying to run the toy example and it gives me the error below.

![image](https://github.com/awesome-spectral-indices/spyndex/assets/136606884/2baf5ba5-50bd-4baa-99dc-7f3b59d8a4a0)

Here is the example I am trying to run.
![image](https://github.com/awesome-spectral-indices/spyndex/assets/136606884/006d5aeb-e181-4cc9-b33d-61ba4d451735)

**Comment by davemlz** [comment]
Fixed! ;)
